baseURL = 'https://qubit-architect.pages.dev/'
languageCode = 'en-us'
title = 'The Qubit Architect'
theme = 'archie'
copyright = "toftpokk"

pygmentsstyle = "one-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[pagination]
  pagerSize = 3

[params]
  mode="dark"
  useCDN=false
  subtitle="Learning Quantum Computing One Qubit at a Time"
  mathjax = true
  katex = true

[permalinks]
  posts = "/posts/:year/:slug"

[outputFormats]
  [outputFormats.RSS]
    baseName = "posts"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 100
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = true
    type = 'basic'
    weight = 80


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/toftpokk"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/toftpokk"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Rss"
url = "/posts.xml"
weight = 4
