baseURL = 'https://quantum-computing.pages.dev/'
languageCode = 'en-us'
title = 'Quantum Computing'
theme = 'archie'
copyright = "toftpokk"

pygmentsstyle = "one-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
  pagerSize = 3

[params]
  mode="dark"
  useCDN=false
  subtitle="toftpokk's Quantum Computing Blog"
  mathjax = true
  katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/toftpokk"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/toftpokk"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Rss"
url = "/blog.xml"
weight = 4
